name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}        

    - name: Peform build
      run: |
        npm install
        npm run build
      
    - name: Upload dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    - name: Upload site
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: site/deploy

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push'
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: site/deploy
        CLEAN: true